version: "3.9"

services:

  dev_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gearvault_dev
      POSTGRES_PASSWORD: gearvault_dev
      POSTGRES_DB: gearvault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: